### ISSUE TITLE
Practica_con_interfaz_grafica_con-interctividad

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-tec-design#1]
[DOcumentación_ Visual_Studio_XU_UI_3er-reporte.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-tec-design/files/14316480/DOcumentacion_.Visual_Studio_XU_UI_3er-reporte.pdf)

Equipo integrado por:
Daisy Gonzalez Lita 
Maribel Santiago Bautista

**Comment by marxgonzalez29** [comment]
Con base a lo que se indica en la rúbrica para su elaboración, cumple con las expectativas deseadas, además tiene una buena presentación y buenas imágenes visuales, solo algunas fallas de ortografía...
98/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
